spring:
  application:
    name: KruchkovTask4
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:~:test;
    username: sa
    password:
    h2:
      console:
        enabled: true
  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: true
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  sql:
    init:
      mode: always
logging:
  level :
  org.springframework:
#
    file:
      name: src/main/resources/LOG/KruchkovTask4.log
      root: ON
file:
  path: src/main/resources/DATA
  #fileReader:
 # class: Kruuchkov.Task4.FileReader
  #propertes:
 #   dirName: D:\work\Обучение\2024\CFT_java\KruchkovTask4\src\main\resources


